# Travis CI configuration file.

dist: trusty

language: php

php:
    - 7.1

services:
    - postgresql

addons:
    chrome: stable

before_install:
    - phpenv config-rm xdebug.ini
    - sudo apt-get update
    - sudo apt-get install language-pack-es
    - sudo /etc/init.d/postgresql stop
    - sudo /etc/init.d/postgresql start 9.6

install:
    - composer install --no-interaction

before_script:
    - db/create.sh travis
    - db/load.sh test
    - tests/download-chromedriver.sh
    - tests/run-acceptance.sh
    - sleep 3

script:
    - vendor/bin/codecept run
    - vendor/bin/phpcs

notifications:
    email: false

# # Cache folder, you can delete cache from Travis CI web interface
# cache:
#     directories:
#         - vendor
#         - $HOME/.composer/cache
