# Travis CI configuration file.

language: php

php:
    - 7.1

before_install: phpenv config-rm xdebug.ini

install:
    - composer install --no-interaction

script:
    - vendor/bin/codecept run

# Cache folder, you can delete cache from Travis CI web interface
cache:
    directories:
        - vendor
        - $HOME/.composer/cache

